### PR TITLE
Fixes following cuelang.org imports

### PR DESCRIPTION
**Pull request by jpluscplusm**
as per commits.

### CODE REVIEW

**Comment by jpluscplusm** [comment]
This is marked as WIP/draft pending the release of CUE `v0.11.0-alpha.4`, which is anticipated to loosen the jsonschema "strict" default such that this PR can be updated to **not** mention the `cue import jsonschema+strictFeatures=0:` change that's currently proposed.

**Comment by mvdan** [comment]
The change in question is now in master: https://review.gerrithub.io/c/cue-lang/cue/+/1202635

We will do alpha.4 later this week.

**Comment by mvdan** [comment]
Is this ready to review?

Also, just to confirm, this should be just mirroring changes from the source of truth inside cuelang.org?

**Comment by jpluscplusm** [comment]
> Is this ready to review?

This is ready to review.

> Also, just to confirm, this should be just mirroring changes from the source of truth inside cuelang.org?

It mirrors their state, but (due to slight historic drift) might not directly reflect any specific set of changes you've seen in an "upstream" CL.

**Review by mvdan — APPROVED** [review]

**Pull request merged**
